### ISSUE TITLE
Inquiry on the experimental results for uniform random TokenMix

### ISSUE THREAD

**Issue by cmsflash** [Sense-X/TokenMix#5]
The paper briefly mentioned that uniform random TokenMix is ineffective for CNNs but beneficial for Transformers. However, I did not find empirical numbers for these claims. Could you provide the numbers for comparison with CutMix as well as structured random TokenMix?

**Comment by jihaonew** [comment]
Hi, the comparison is in Table 8 of our [paper](https://arxiv.org/pdf/2207.08409.pdf).

|Mask type|Region|Random|
|:-:|:-:|:-:|
|Deit-T|72.2|**72.7**|
|ResNet50|**79.3**|78.3|

Note that the region mask is used by CutMix.

**Comment by cmsflash** [comment]
I see. Sorry for missing the table when reading your paper.

Mask type | Region | Random | Block
-- | -- | -- | --
Deit-T | 72.2 | **72.7** | **72.7**
DeiT-S | 79.8 | **80.6** | **80.6**
ResNet-50 | 79.3 | 78.3 | **79.7**

From the full table, it seems that random and block sampling work similarly well for ViTs. Block sampling is only advantageous on CNNs?

Also, when apply to CNNs, is the method more like just BlockMix because there is no notion of tokens?

**Comment by jihaonew** [comment]
> Block sampling is only advantageous on CNNs?

Yes. 

> BlockMix for CNNs

This one should be more accurate.

**Comment by cmsflash** [comment]
Thank you so much for the classifications. An awesome work!
